development:
  secret_key_base: 6bb4359b0e5bc63d0c200b87c6c7a76d69de18f401ecb8d414bf9a29c8267e70cc9c876ef64fa8deb323f2f410e1a30ffc87908db7e9a50a3bdc1ac3e732d55e
  http_basic_user: <%= ENV["HTTP_BASIC_USER"] %>
  http_basic_password: <%= ENV["HTTP_BASIC_PASSWORD"] %>

test:
  secret_key_base: d15f1ab14faa84345d5a8909129f859d192f22a61c462e6154b463a7d692c9393f6051cddb6f266b6be655434f0ace4a5a54317e537bfaa3919bf5746575f4cf
  http_basic_user: <%= ENV["HTTP_BASIC_USER"] %>
  http_basic_password: <%= ENV["HTTP_BASIC_PASSWORD"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  http_basic_user: <%= ENV["HTTP_BASIC_USER"] %>
  http_basic_password: <%= ENV["HTTP_BASIC_PASSWORD"] %>
